# Discord API settings
discord:
  token: "TOKEN"                        # Provide your token here
  intents:                              # Don't touch this unless you know what you're doing

# Bot settings        
options:        
  prefix: "?"                           # Command prefix
  logging:                              
    # WARNING! If you diable all logging and something breaks, fixing it will be very difficult. 
    # Recommend you leave console logging enabled as a minimum
    logToConsole: True                  # Enable logging to console
    logToFile: False                    # Enable logging  to file
    logFilePath: "path/to/log.txt"      # Log location

